### ISSUE TITLE
Mention requirement to use checkout

### ISSUE THREAD

**Issue by kalikiana** [hadolint/hadolint-action#25]
I think the usage example should include the *checkout* action:

    uses: actions/checkout@v2

Because otherwise you get this error trying to use *hadolint*:

    hadolint: ./container/webui/Dockerfile: openBinaryFile: does not exist (No such file or directory)

**Comment by brpaz** [comment]
Well, I can add that, I thought it was pretty obvious, since if you don´t checkout your code, how hadolint will have anything to analyze?

**Comment by lorenzo** [comment]
I think it would be idea to have a full copy-pasteable example @brpaz

**Comment by kalikiana** [comment]
Yes. If you provide an example like that I kind of expect it to work as-is.

**Comment by lorenzo** [comment]
@kalikiana would you like to contribute the example to the readme?
