### ISSUE TITLE
How to update to hadolint 2.4.0?

### ISSUE THREAD

**Issue by mloskot** [hadolint/hadolint-action#31]
I hope it's OK to ask questions via GitHub, couldn't find an alternative channel.

The [hadolint 2.4.0](https://github.com/hadolint/hadolint/releases/tag/v2.4.0) now supports the [language-docker 10.0.0](https://github.com/hadolint/language-docker/releases/tag/10.0.0) with 
- Fixed parsing of dockerfiles including a custom escape char

By the way, thank you @lorenzo and @m-ildefons very much for fixing this!

Would it be possible to update the action to use those latest?

**Comment by lorenzo** [comment]
the action code needs to be updated, I won't have time this weekend to fix it, but I'd gladly accept a PR if you want to help

**Comment by mloskot** [comment]
I thought it needs rebuild of Docker image.
Thank you @m-ildefons for your help with the update!
