### ISSUE TITLE
Missing Changelog

### ISSUE THREAD

**Issue by Justintime50** [hadolint/hadolint-action#37]
I went looking for an easy way to view changes made to this project and noticed there is no changelog. I'd be more than happy to add a PR that includes a CHANGELOG but wanted to see if that's something you'd want added since that'd alter your releasing workflow a tad.

Let me know!

**Comment by jimrazmus** [comment]
Github 'releases' provides a rough equivalent/alternative. Reference https://github.com/hadolint/hadolint-action/releases

**Comment by Justintime50** [comment]
Unfortunately the items listed there are pretty vague, but yeah that's certainly an option. This has sat for some time with no input until today. I'll close.
