### ISSUE TITLE
Do you support config file as input?

### ISSUE THREAD

**Issue by FinalDes** [hadolint/hadolint-action#5]
Hadolint --config option?

**Comment by brpaz** [comment]
Not natively, but you could try using the "dockerfile" input argument which is passed straight to the hadolint command:

```
     uses: brpaz/hadolint-action@master
      with:
         dockerfile:  "--config xxx"
```

I might improve this to allow specifying a config option but for now since I always use the default .hadolint,yaml it´s not a need for me. PRs are always welcome

**Comment by FinalDes** [comment]
plz mention the default hadolint config file is `.hadolint,yaml` in README.md file

**Comment by josegonzalez** [comment]
Would be great to be able to specify the `.hadolint.yml` path. I put all of mine in `.github/linters` at the moment.
